"""Add RescheduleRequest model

Revision ID: 25e809e16c43
Revises: 6a4ad6dd5d62
Create Date: 2026-01-20 07:26:49.289056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25e809e16c43'
down_revision = '6a4ad6dd5d62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reschedule_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_schedule_id', sa.Integer(), nullable=True),
    sa.Column('original_booking_id', sa.Integer(), nullable=True),
    sa.Column('original_date', sa.Date(), nullable=False),
    sa.Column('original_timeslot_id', sa.Integer(), nullable=False),
    sa.Column('original_teacher_id', sa.Integer(), nullable=False),
    sa.Column('new_date', sa.Date(), nullable=False),
    sa.Column('new_timeslot_id', sa.Integer(), nullable=False),
    sa.Column('new_teacher_id', sa.Integer(), nullable=False),
    sa.Column('class_enrollment_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('request_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('new_booking_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['class_enrollment_id'], ['class_enrollments.id'], ),
    sa.ForeignKeyConstraint(['new_booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['new_teacher_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['new_timeslot_id'], ['timeslots.id'], ),
    sa.ForeignKeyConstraint(['original_booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['original_teacher_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['original_timeslot_id'], ['timeslots.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_schedule_id'], ['student_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reschedule_requests')
    # ### end Alembic commands ###
