"""Add MasterClass model

Revision ID: 4483d393c268
Revises: f5a33da0925c
Create Date: 2026-01-13 10:48:11.545614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4483d393c268'
down_revision = 'f5a33da0925c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_max_izin', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('program_classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('master_class_id', sa.Integer(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.create_foreign_key(None, 'master_classes', ['master_class_id'], ['id'])

    with op.batch_alter_table('teacher_skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('master_class_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'master_classes', ['master_class_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_skills', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('master_class_id')

    with op.batch_alter_table('program_classes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('master_class_id')

    op.drop_table('master_classes')
    # ### end Alembic commands ###
