"""Add Syllabus and Portfolio models

Revision ID: 6c8b2302b14e
Revises: a5496a475c11
Create Date: 2026-01-07 20:34:04.131680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c8b2302b14e'
down_revision = 'a5496a475c11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('syllabus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_class_id', sa.Integer(), nullable=False),
    sa.Column('topic_name', sa.String(length=200), nullable=False),
    sa.Column('sessions', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['program_class_id'], ['program_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_enrollment_id', sa.Integer(), nullable=False),
    sa.Column('syllabus_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=200), nullable=False),
    sa.Column('drive_file_id', sa.String(length=100), nullable=True),
    sa.Column('drive_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_enrollment_id'], ['class_enrollments.id'], ),
    sa.ForeignKeyConstraint(['syllabus_id'], ['syllabus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drive_folder_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('drive_folder_id')

    op.drop_table('portfolios')
    op.drop_table('syllabus')
    # ### end Alembic commands ###
