"""Second migration

Revision ID: a67e8889bed3
Revises: 119dcf0daf52
Create Date: 2025-12-16 20:12:46.296466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a67e8889bed3'
down_revision = '119dcf0daf52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sessions_remaining', sa.Integer(), nullable=True))

    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_sessions', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['phone_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_column('total_sessions')

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_column('sessions_remaining')

    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
