"""Add master_class_id to TeacherAvailability

Revision ID: aca04a6858f1
Revises: 4483d393c268
Create Date: 2026-01-13 12:07:34.352203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aca04a6858f1'
down_revision = '4483d393c268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_availabilities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('master_class_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'master_classes', ['master_class_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_availabilities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('master_class_id')

    # ### end Alembic commands ###
