"""Add first_class_date to enrollment

Revision ID: be9ae550a65c
Revises: aca04a6858f1
Create Date: 2026-01-13 13:38:32.987131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be9ae550a65c'
down_revision = 'aca04a6858f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_class_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_column('first_class_date')

    # ### end Alembic commands ###
